services:
  primevue_breeze_nuxt:
    build: .
    container_name: primevue_breeze_nuxt
    entrypoint: /bin/sh
    working_dir: /web
    volumes:
      - '.:/web'
      #- 'nuxt-satic-output:/web/dist' # revisit later
    tty: true
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.primevue_breeze_nuxt.rule=Host(`nuxt.breeze-api.localhost`)"
      - "traefik.http.services.primevue_breeze_nuxt.loadbalancer.server.port=${TRAEFIK_PORT}"
    networks:
      - proxy

  primevue_breeze_nuxt_static: # preview the generated site (keeps top level domain for Laravel API)
    image: nginx:alpine
    container_name: primevue_breeze_nuxt_static
    volumes:
      - 'nuxt-satic-output:/usr/share/nginx/html'
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.primevue_breeze_nuxt_static.rule=Host(`nuxt-preview.breeze-api.localhost`)"
      - "traefik.http.services.primevue_breeze_nuxt_static.loadbalancer.server.port=80"
    networks:
      - proxy
    depends_on:
      - primevue_breeze_nuxt

networks:
  proxy:
    name: "traefik_network"

volumes:
  nuxt-satic-output:
